# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s1i-wnFV5QsPTwGfbMXIzmDMIS2BeRCp
"""

#ETE PORTO DIGITAL
#PROFESSOR: CLOVES ROCHA
#ESTUDANTE:KAROLINA SALES
nomes= ['Karol','Alana','Aline']
for n in nomes:
  print(n)